const {cos} = require('react-native-reanimated');

export const COLLECTIONS_ITEM = 'COLLECTIONS_ITEM';
export const FETCH_COLLECTIONS_START = 'FETCH_COLLECTIONS_START';
export const FETCH_COLLECTIONS_SUCCESS = 'FETCH_COLLECTIONS_SUCCESS';
export const FETCH_COLLECTIONS_FAILURE = 'FETCH_COLLECTIONS_FAILURE';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const DELETE_CART = 'DELETE_CART';
export const OPEN_MODAL_ITEM = 'OPEN_MODAL_ITEM';
